# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomAppOnTheFly' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CustomAppOnTheFly

  target 'CustomAppOnTheFly-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomAppOnTheFlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CustomAppOnTheFly-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CustomAppOnTheFly-tvOS

  target 'CustomAppOnTheFly-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
